version: '3.8'

services:
  # Backend API Service
  pegasus-nest:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pegasus-nest-api
    restart: unless-stopped
    networks:
      - pegasus-network
    volumes:
      - ./generated:/app/generated
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=3000

  # Frontend Service
  pegasus-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pegasus-nest-frontend
    restart: unless-stopped
    networks:
      - pegasus-network
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://37.114.41.124
    depends_on:
      - pegasus-nest

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: pegasus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pegasus-network
    depends_on:
      - pegasus-nest
      - pegasus-frontend

networks:
  pegasus-network:
    driver: bridge
