version: '3.8'

services:
  # Backend API Service
  pegasus-nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pegasus-nest-api
    restart: unless-stopped
    networks:
      - pegasus-network
    volumes:
      - ./generated:/app/generated
      - ./logs:/app/logs
      - ./public:/app/public
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Frontend Service
  pegasus-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pegasus-nest-frontend
    restart: unless-stopped
    networks:
      - pegasus-network
    env_file:
      - ./frontend/.env.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://pegasus-nest:3000
    depends_on:
      pegasus-nest:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: pegasus-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    networks:
      - pegasus-network
    depends_on:
      pegasus-nest:
        condition: service_healthy
      pegasus-frontend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'nginx', '-t']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pegasus-network:
    driver: bridge

volumes:
  nginx-logs:
  generated_data:
  public_data:
