name: Build and Test Pegasus Nest API

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Verify pnpm installation
        run: |
          pnpm --version
          echo "Checking lockfile..."
          ls -la pnpm-lock.yaml || echo "Lockfile missing"

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          echo "Installing API dependencies..."
          if pnpm install --frozen-lockfile --dry-run; then
            echo "Using frozen lockfile..."
            pnpm install --frozen-lockfile
          else
            echo "Lockfile incompatible, regenerating..."
            pnpm install
          fi

      - name: Build API
        run: pnpm run build

      - name: Run API tests (if available)
        run: pnpm run test || echo "No tests configured"
        continue-on-error: true

  # Automatic deployment has been disabled
  # To deploy manually, run the deployment scripts on the VPS:
  # 1. Copy files to VPS: rsync -avz ./ root@37.114.41.124:/opt/pegasus-nest/
  # 2. SSH to VPS: ssh root@37.114.41.124
  # 3. Run deployment: cd /opt/pegasus-nest && ./deploy-vps.sh
